# Generated by Django 3.0.8 on 2020-07-20 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nutrientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recomendado',
            fields=[
                ('nutriente_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='nutrientes.Nutriente')),
                ('massa', models.FloatField()),
                ('idade', models.IntegerField()),
            ],
            options={
                'db_table': 'recomendado',
            },
            bases=('nutrientes.nutriente',),
        ),
    ]
