# Generated by Django 3.0.8 on 2020-09-27 05:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dados_bancarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_banco', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(999)])),
                ('nome_banco', models.CharField(max_length=150)),
                ('agencia', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(9999)])),
                ('conta', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(99999999999)])),
                ('digito_conta', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(9)])),
                ('tipo_de_conta', models.CharField(choices=[('CR', 'Corrente'), ('PO', 'Poupança'), ('PG', 'Pagamento')], default='CR', max_length=2)),
            ],
        ),
    ]
