# Generated by Django 3.0.8 on 2020-10-29 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dados_bancarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dados_bancarios',
            name='tipo_de_conta',
            field=models.CharField(choices=[('CR', 'Corrente'), ('PO', 'Poupança'), ('PG', 'Pagamento'), ('PX', 'PIX')], default='CR', max_length=2),
        ),
    ]
