# Generated by Django 3.0.8 on 2020-09-03 18:52

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produto', '0001_initial'),
        ('indicacao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=6)),
                ('data_efetivada', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('indicacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indicacao.Indicacao')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produto.Produto')),
            ],
            options={
                'verbose_name_plural': 'Indicações',
            },
        ),
    ]
