INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (5, 'Cereais e derivados', 'Arroz, tipo 2, cozido');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (6, 'Cereais e derivados', 'Arroz, tipo 2, cru');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (9, 'Cereais e derivados', 'Biscoito, doce, recheado com chocolate');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (10, 'Cereais e derivados', 'Biscoito, doce, recheado com morango');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (11, 'Cereais e derivados', 'Biscoito, doce, wafer, recheado de chocolate');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (12, 'Cereais e derivados', 'Biscoito, doce, wafer, recheado de morango');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (13, 'Cereais e derivados', 'Biscoito, salgado, cream cracker');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (14, 'Cereais e derivados', 'Bolo, mistura para');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (15, 'Cereais e derivados', 'Bolo, pronto, aipim');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (16, 'Cereais e derivados', 'Bolo, pronto, chocolate');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (17, 'Cereais e derivados', 'Bolo, pronto, coco');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (18, 'Cereais e derivados', 'Bolo, pronto, milho');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (19, 'Cereais e derivados', 'Canjica, branca, crua');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (20, 'Cereais e derivados', 'Canjica, com leite integral');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (21, 'Cereais e derivados', 'Cereais, milho, flocos, com sal');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (22, 'Cereais e derivados', 'Cereais, milho, flocos, sem sal');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (23, 'Cereais e derivados', 'Cereais, mingau, milho, infantil');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (24, 'Cereais e derivados', 'Cereais, mistura para vitamina, trigo, cevada e aveia');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (25, 'Cereais e derivados', 'Cereal matinal, milho');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (26, 'Cereais e derivados', 'Cereal matinal, milho, açúcar');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (27, 'Cereais e derivados', 'Creme de arroz, pó');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (28, 'Cereais e derivados', 'Creme de milho, pó');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (2, 'Cereais e derivados', 'Arroz, integral, cru');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (3, 'Cereais e derivados', 'Arroz, tipo 1, cozido');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (4, 'Cereais e derivados', 'Arroz, tipo 1, cru');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (7, 'Cereais e derivados', 'Aveia, flocos, crua');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (8, 'Cereais e derivados', 'Biscoito, doce, maisena');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (29, 'Cereais e derivados', 'Curau, milho verde');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (30, 'Cereais e derivados', 'Curau, milho verde, mistura para');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (31, 'Cereais e derivados', 'Farinha, de arroz, enriquecida');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (32, 'Cereais e derivados', 'Farinha, de centeio, integral');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (33, 'Cereais e derivados', 'Farinha, de milho, amarela');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (34, 'Cereais e derivados', 'Farinha, de rosca');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (35, 'Cereais e derivados', 'Farinha, de trigo');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (36, 'Cereais e derivados', 'Farinha, láctea, de cereais');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (37, 'Cereais e derivados', 'Lasanha, massa fresca, cozida');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (38, 'Cereais e derivados', 'Lasanha, massa fresca, crua');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (39, 'Cereais e derivados', 'Macarrão, instantâneo');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (40, 'Cereais e derivados', 'Macarrão, trigo, cru');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (41, 'Cereais e derivados', 'Macarrão, trigo, cru, com ovos');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (42, 'Cereais e derivados', 'Milho, amido, cru');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (43, 'Cereais e derivados', 'Milho, fubá, cru');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (44, 'Cereais e derivados', 'Milho, verde, cru');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (45, 'Cereais e derivados', 'Milho, verde, enlatado, drenado');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (46, 'Cereais e derivados', 'Mingau tradicional, pó');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (47, 'Cereais e derivados', 'Pamonha, barra para cozimento, pré-cozida');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (48, 'Cereais e derivados', 'Pão, aveia, forma');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (49, 'Cereais e derivados', 'Pão, de soja');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (50, 'Cereais e derivados', 'Pão, glúten, forma');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (51, 'Cereais e derivados', 'Pão, milho, forma');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (52, 'Cereais e derivados', 'Pão, trigo, forma, integral');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (53, 'Cereais e derivados', 'Pão, trigo, francês');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (54, 'Cereais e derivados', 'Pão, trigo, sovado');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (55, 'Cereais e derivados', 'Pastel, de carne, cru');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (56, 'Cereais e derivados', 'Pastel, de carne, frito');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (57, 'Cereais e derivados', 'Pastel, de queijo, cru');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (58, 'Cereais e derivados', 'Pastel, de queijo, frito');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (59, 'Cereais e derivados', 'Pastel, massa, crua');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (60, 'Cereais e derivados', 'Pastel, massa, frita');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (61, 'Cereais e derivados', 'Pipoca, com óleo de soja, sem sal');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (62, 'Cereais e derivados', 'Polenta, pré-cozida');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (63, 'Cereais e derivados', 'Torrada, pão francês');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (64, 'Verduras, hortaliças e derivados', 'Abóbora, cabotian, cozida');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (65, 'Verduras, hortaliças e derivados', 'Abóbora, cabotian, crua');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (66, 'Verduras, hortaliças e derivados', 'Abóbora, menina brasileira, crua');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (67, 'Verduras, hortaliças e derivados', 'Abóbora, moranga, crua');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (68, 'Verduras, hortaliças e derivados', 'Abóbora, moranga, refogada');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (69, 'Verduras, hortaliças e derivados', 'Abóbora, pescoço, crua');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (70, 'Verduras, hortaliças e derivados', 'Abobrinha, italiana, cozida');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (71, 'Verduras, hortaliças e derivados', 'Abobrinha, italiana, crua');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (72, 'Verduras, hortaliças e derivados', 'Abobrinha, italiana, refogada');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (73, 'Verduras, hortaliças e derivados', 'Abobrinha, paulista, crua');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (74, 'Verduras, hortaliças e derivados', 'Acelga, crua');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (75, 'Verduras, hortaliças e derivados', 'Agrião, cru');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (76, 'Verduras, hortaliças e derivados', 'Aipo, cru');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (77, 'Verduras, hortaliças e derivados', 'Alface, americana, crua');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (78, 'Verduras, hortaliças e derivados', 'Alface, crespa, crua');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (79, 'Verduras, hortaliças e derivados', 'Alface, lisa, crua');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (80, 'Verduras, hortaliças e derivados', 'Alface, roxa, crua');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (81, 'Verduras, hortaliças e derivados', 'Alfavaca, crua');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (82, 'Verduras, hortaliças e derivados', 'Alho, cru');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (83, 'Verduras, hortaliças e derivados', 'Alho-poró, cru');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (84, 'Verduras, hortaliças e derivados', 'Almeirão, cru');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (85, 'Verduras, hortaliças e derivados', 'Almeirão, refogado');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (86, 'Verduras, hortaliças e derivados', 'Batata, baroa, cozida');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (87, 'Verduras, hortaliças e derivados', 'Batata, baroa, crua');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (88, 'Verduras, hortaliças e derivados', 'Batata, doce, cozida');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (89, 'Verduras, hortaliças e derivados', 'Batata, doce, crua');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (90, 'Verduras, hortaliças e derivados', 'Batata, frita, tipo chips, industrializada');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (91, 'Verduras, hortaliças e derivados', 'Batata, inglesa, cozida');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (92, 'Verduras, hortaliças e derivados', 'Batata, inglesa, crua');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (93, 'Verduras, hortaliças e derivados', 'Batata, inglesa, frita');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (94, 'Verduras, hortaliças e derivados', 'Batata, inglesa, sauté');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (95, 'Verduras, hortaliças e derivados', 'Berinjela, cozida');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (96, 'Verduras, hortaliças e derivados', 'Berinjela, crua');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (97, 'Verduras, hortaliças e derivados', 'Beterraba, cozida');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (98, 'Verduras, hortaliças e derivados', 'Beterraba, crua');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (99, 'Verduras, hortaliças e derivados', 'Biscoito, polvilho doce');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (100, 'Verduras, hortaliças e derivados', 'Brócolis, cozido');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (101, 'Verduras, hortaliças e derivados', 'Brócolis, cru');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (102, 'Verduras, hortaliças e derivados', 'Cará, cozido');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (103, 'Verduras, hortaliças e derivados', 'Cará, cru');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (104, 'Verduras, hortaliças e derivados', 'Caruru, cru');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (105, 'Verduras, hortaliças e derivados', 'Catalonha, crua');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (106, 'Verduras, hortaliças e derivados', 'Catalonha, refogada');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (107, 'Verduras, hortaliças e derivados', 'Cebola, crua');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (108, 'Verduras, hortaliças e derivados', 'Cebolinha, crua');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (109, 'Verduras, hortaliças e derivados', 'Cenoura, cozida');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (110, 'Verduras, hortaliças e derivados', 'Cenoura, crua');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (111, 'Verduras, hortaliças e derivados', 'Chicória, crua');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (112, 'Verduras, hortaliças e derivados', 'Chuchu, cozido');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (113, 'Verduras, hortaliças e derivados', 'Chuchu, cru');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (114, 'Verduras, hortaliças e derivados', 'Coentro, folhas desidratadas');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (115, 'Verduras, hortaliças e derivados', 'Couve, manteiga, crua');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (116, 'Verduras, hortaliças e derivados', 'Couve, manteiga, refogada');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (117, 'Verduras, hortaliças e derivados', 'Couve-flor, crua');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (118, 'Verduras, hortaliças e derivados', 'Couve-flor, cozida');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (119, 'Verduras, hortaliças e derivados', 'Espinafre, Nova Zelândia, cru');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (120, 'Verduras, hortaliças e derivados', 'Espinafre, Nova Zelândia, refogado');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (121, 'Verduras, hortaliças e derivados', 'Farinha, de mandioca, crua');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (122, 'Verduras, hortaliças e derivados', 'Farinha, de mandioca, torrada');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (123, 'Verduras, hortaliças e derivados', 'Farinha, de puba');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (124, 'Verduras, hortaliças e derivados', 'Fécula, de mandioca');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (125, 'Verduras, hortaliças e derivados', 'Feijão, broto, cru');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (126, 'Verduras, hortaliças e derivados', 'Inhame, cru');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (127, 'Verduras, hortaliças e derivados', 'Jiló, cru');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (128, 'Verduras, hortaliças e derivados', 'Jurubeba, crua');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (129, 'Verduras, hortaliças e derivados', 'Mandioca, cozida');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (130, 'Verduras, hortaliças e derivados', 'Mandioca, crua');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (131, 'Verduras, hortaliças e derivados', 'Mandioca, farofa, temperada');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (132, 'Verduras, hortaliças e derivados', 'Mandioca, frita');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (133, 'Verduras, hortaliças e derivados', 'Manjericão, cru');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (134, 'Verduras, hortaliças e derivados', 'Maxixe, cru');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (135, 'Verduras, hortaliças e derivados', 'Mostarda, folha, crua');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (136, 'Verduras, hortaliças e derivados', 'Nhoque, batata, cozido');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (137, 'Verduras, hortaliças e derivados', 'Nabo, cru');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (138, 'Verduras, hortaliças e derivados', 'Palmito, Juçara, em conserva');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (200, 'Frutas e derivados', 'Goiaba, vermelha, com casca, crua');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (201, 'Frutas e derivados', 'Graviola, crua');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (202, 'Frutas e derivados', 'Graviola, polpa, congelada');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (139, 'Verduras, hortaliças e derivados', 'Palmito, pupunha, em conserva');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (140, 'Verduras, hortaliças e derivados', 'Pão, de queijo, assado');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (141, 'Verduras, hortaliças e derivados', 'Pão, de queijo, cru');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (142, 'Verduras, hortaliças e derivados', 'Pepino, cru');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (143, 'Verduras, hortaliças e derivados', 'Pimentão, amarelo, cru');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (144, 'Verduras, hortaliças e derivados', 'Pimentão, verde, cru');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (145, 'Verduras, hortaliças e derivados', 'Pimentão, vermelho, cru');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (146, 'Verduras, hortaliças e derivados', 'Polvilho, doce');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (147, 'Verduras, hortaliças e derivados', 'Quiabo, cru');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (148, 'Verduras, hortaliças e derivados', 'Rabanete, cru');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (149, 'Verduras, hortaliças e derivados', 'Repolho, branco, cru');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (150, 'Verduras, hortaliças e derivados', 'Repolho, roxo, cru');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (151, 'Verduras, hortaliças e derivados', 'Repolho, roxo, refogado');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (152, 'Verduras, hortaliças e derivados', 'Rúcula, crua');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (153, 'Verduras, hortaliças e derivados', 'Salsa, crua');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (154, 'Verduras, hortaliças e derivados', 'Seleta de legumes, enlatada');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (155, 'Verduras, hortaliças e derivados', 'Serralha, crua');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (156, 'Verduras, hortaliças e derivados', 'Taioba, crua');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (157, 'Verduras, hortaliças e derivados', 'Tomate, com semente, cru');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (158, 'Verduras, hortaliças e derivados', 'Tomate, extrato');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (159, 'Verduras, hortaliças e derivados', 'Tomate, molho industrializado');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (160, 'Verduras, hortaliças e derivados', 'Tomate, purê');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (161, 'Verduras, hortaliças e derivados', 'Tomate, salada');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (162, 'Verduras, hortaliças e derivados', 'Vagem, crua');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (163, 'Frutas e derivados', 'Abacate, cru');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (164, 'Frutas e derivados', 'Abacaxi, cru');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (165, 'Frutas e derivados', 'Abacaxi, polpa, congelada');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (166, 'Frutas e derivados', 'Abiu, cru');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (167, 'Frutas e derivados', 'Açaí, polpa, com xarope de guaraná e glucose');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (168, 'Frutas e derivados', 'Açaí, polpa, congelada');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (169, 'Frutas e derivados', 'Acerola, crua');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (170, 'Frutas e derivados', 'Acerola, polpa, congelada');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (171, 'Frutas e derivados', 'Ameixa, calda, enlatada');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (172, 'Frutas e derivados', 'Ameixa, crua');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (173, 'Frutas e derivados', 'Ameixa, em calda, enlatada, drenada');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (174, 'Frutas e derivados', 'Atemóia, crua');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (175, 'Frutas e derivados', 'Banana, da terra, crua');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (176, 'Frutas e derivados', 'Banana, doce em barra');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (177, 'Frutas e derivados', 'Banana, figo, crua');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (178, 'Frutas e derivados', 'Banana, maçã, crua');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (179, 'Frutas e derivados', 'Banana, nanica, crua');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (180, 'Frutas e derivados', 'Banana, ouro, crua');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (181, 'Frutas e derivados', 'Banana, pacova, crua');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (182, 'Frutas e derivados', 'Banana, prata, crua');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (1, 'Cereais e derivados', 'Arroz, integral, cozido');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (183, 'Frutas e derivados', 'Cacau, cru');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (184, 'Frutas e derivados', 'Cajá-Manga, cru');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (185, 'Frutas e derivados', 'Cajá, polpa, congelada');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (186, 'Frutas e derivados', 'Caju, cru');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (187, 'Frutas e derivados', 'Caju, polpa, congelada');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (188, 'Frutas e derivados', 'Caju, suco concentrado, envasado');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (189, 'Frutas e derivados', 'Caqui, chocolate, cru');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (190, 'Frutas e derivados', 'Carambola, crua');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (191, 'Frutas e derivados', 'Ciriguela, crua');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (192, 'Frutas e derivados', 'Cupuaçu, cru');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (193, 'Frutas e derivados', 'Cupuaçu, polpa, congelada');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (194, 'Frutas e derivados', 'Figo, cru');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (195, 'Frutas e derivados', 'Figo, enlatado, em calda');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (196, 'Frutas e derivados', 'Fruta-pão, crua');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (197, 'Frutas e derivados', 'Goiaba, branca, com casca, crua');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (198, 'Frutas e derivados', 'Goiaba, doce em pasta');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (199, 'Frutas e derivados', 'Goiaba, doce, cascão');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (203, 'Frutas e derivados', 'Jabuticaba, crua');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (204, 'Frutas e derivados', 'Jaca, crua');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (205, 'Frutas e derivados', 'Jambo, cru');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (206, 'Frutas e derivados', 'Jamelão, cru');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (207, 'Frutas e derivados', 'Kiwi, cru');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (208, 'Frutas e derivados', 'Laranja, baía, crua');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (209, 'Frutas e derivados', 'Laranja, baía, suco');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (210, 'Frutas e derivados', 'Laranja, da terra, crua');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (211, 'Frutas e derivados', 'Laranja, da terra, suco');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (212, 'Frutas e derivados', 'Laranja, lima, crua');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (213, 'Frutas e derivados', 'Laranja, lima, suco');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (214, 'Frutas e derivados', 'Laranja, pêra, crua');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (215, 'Frutas e derivados', 'Laranja, pêra, suco');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (216, 'Frutas e derivados', 'Laranja, valência, crua');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (217, 'Frutas e derivados', 'Laranja, valência, suco');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (218, 'Frutas e derivados', 'Limão, cravo, suco');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (219, 'Frutas e derivados', 'Limão, galego, suco');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (220, 'Frutas e derivados', 'Limão, tahiti, cru');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (221, 'Frutas e derivados', 'Maçã, Argentina, com casca, crua');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (222, 'Frutas e derivados', 'Maçã, Fuji, com casca, crua');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (223, 'Frutas e derivados', 'Macaúba, crua');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (224, 'Frutas e derivados', 'Mamão, doce em calda, drenado');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (225, 'Frutas e derivados', 'Mamão, Formosa, cru');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (226, 'Frutas e derivados', 'Mamão, Papaia, cru');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (227, 'Frutas e derivados', 'Mamão verde, doce em calda, drenado');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (228, 'Frutas e derivados', 'Manga, Haden, crua');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (229, 'Frutas e derivados', 'Manga, Palmer, crua');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (230, 'Frutas e derivados', 'Manga, polpa, congelada');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (231, 'Frutas e derivados', 'Manga, Tommy Atkins, crua');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (232, 'Frutas e derivados', 'Maracujá, cru');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (233, 'Frutas e derivados', 'Maracujá, polpa, congelada');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (234, 'Frutas e derivados', 'Maracujá, suco concentrado, envasado');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (235, 'Frutas e derivados', 'Melancia, crua');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (236, 'Frutas e derivados', 'Melão, cru');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (237, 'Frutas e derivados', 'Mexerica, Murcote, crua');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (238, 'Frutas e derivados', 'Mexerica, Rio, crua');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (239, 'Frutas e derivados', 'Morango, cru');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (240, 'Frutas e derivados', 'Nêspera, crua');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (241, 'Frutas e derivados', 'Pequi, cru');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (242, 'Frutas e derivados', 'Pêra, Park, crua');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (243, 'Frutas e derivados', 'Pêra, Williams, crua');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (244, 'Frutas e derivados', 'Pêssego, Aurora, cru');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (245, 'Frutas e derivados', 'Pêssego, enlatado, em calda');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (246, 'Frutas e derivados', 'Pinha, crua');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (247, 'Frutas e derivados', 'Pitanga, crua');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (248, 'Frutas e derivados', 'Pitanga, polpa, congelada');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (249, 'Frutas e derivados', 'Romã, crua');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (250, 'Frutas e derivados', 'Tamarindo, cru');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (251, 'Frutas e derivados', 'Tangerina, Poncã, crua');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (252, 'Frutas e derivados', 'Tangerina, Poncã, suco');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (253, 'Frutas e derivados', 'Tucumã, cru');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (254, 'Frutas e derivados', 'Umbu, cru');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (255, 'Frutas e derivados', 'Umbu, polpa, congelada');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (256, 'Frutas e derivados', 'Uva, Itália, crua');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (257, 'Frutas e derivados', 'Uva, Rubi, crua');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (258, 'Frutas e derivados', 'Uva, suco concentrado, envasado');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (259, 'Gorduras e óleos', 'Azeite, de dendê');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (260, 'Gorduras e óleos', 'Azeite, de oliva, extra virgem');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (261, 'Gorduras e óleos', 'Manteiga, com sal');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (262, 'Gorduras e óleos', 'Manteiga, sem sal');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (263, 'Gorduras e óleos', 'Margarina, com óleo hidrogenado, com sal (65% de lipídeos)');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (264, 'Gorduras e óleos', 'Margarina, com óleo hidrogenado, sem sal (80% de lipídeos)');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (265, 'Gorduras e óleos', 'Margarina, com óleo interesterificado, com sal (65%de lipídeos)');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (266, 'Gorduras e óleos', 'Margarina, com óleo interesterificado, sem sal (65% de lipídeos)');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (267, 'Gorduras e óleos', 'Óleo, de babaçu');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (268, 'Gorduras e óleos', 'Óleo, de canola');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (269, 'Gorduras e óleos', 'Óleo, de girassol');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (270, 'Gorduras e óleos', 'Óleo, de milho');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (271, 'Gorduras e óleos', 'Óleo, de pequi');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (272, 'Gorduras e óleos', 'Óleo, de soja');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (273, 'Pescados e frutos do mar', 'Abadejo, filé, congelado, assado');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (274, 'Pescados e frutos do mar', 'Abadejo, filé, congelado,cozido');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (275, 'Pescados e frutos do mar', 'Abadejo, filé, congelado, cru');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (276, 'Pescados e frutos do mar', 'Abadejo, filé, congelado, grelhado');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (277, 'Pescados e frutos do mar', 'Atum, conserva em óleo');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (278, 'Pescados e frutos do mar', 'Atum, fresco, cru');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (279, 'Pescados e frutos do mar', 'Bacalhau, salgado, cru');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (280, 'Pescados e frutos do mar', 'Bacalhau, salgado, refogado');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (281, 'Pescados e frutos do mar', 'Cação, posta, com farinha de trigo, frita');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (282, 'Pescados e frutos do mar', 'Cação, posta, cozida');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (283, 'Pescados e frutos do mar', 'Cação, posta, crua');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (284, 'Pescados e frutos do mar', 'Camarão, Rio Grande, grande, cozido');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (285, 'Pescados e frutos do mar', 'Camarão, Rio Grande, grande, cru');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (286, 'Pescados e frutos do mar', 'Camarão, Sete Barbas, sem cabeça, com casca, frito');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (287, 'Pescados e frutos do mar', 'Caranguejo, cozido');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (288, 'Pescados e frutos do mar', 'Corimba, cru');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (289, 'Pescados e frutos do mar', 'Corimbatá, assado');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (290, 'Pescados e frutos do mar', 'Corimbatá, cozido');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (291, 'Pescados e frutos do mar', 'Corvina de água doce, crua');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (292, 'Pescados e frutos do mar', 'Corvina do mar, crua');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (293, 'Pescados e frutos do mar', 'Corvina grande, assada');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (294, 'Pescados e frutos do mar', 'Corvina grande, cozida');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (295, 'Pescados e frutos do mar', 'Dourada de água doce, fresca');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (296, 'Pescados e frutos do mar', 'Lambari, congelado, cru');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (297, 'Pescados e frutos do mar', 'Lambari, congelado, frito');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (298, 'Pescados e frutos do mar', 'Lambari, fresco,cru');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (299, 'Pescados e frutos do mar', 'Manjuba, com farinha de trigo, frita');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (300, 'Pescados e frutos do mar', 'Manjuba, frita');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (301, 'Pescados e frutos do mar', 'Merluza, filé, assado');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (302, 'Pescados e frutos do mar', 'Merluza, filé, cru');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (303, 'Pescados e frutos do mar', 'Merluza, filé, frito');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (304, 'Pescados e frutos do mar', 'Pescada, branca, crua');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (305, 'Pescados e frutos do mar', 'Pescada, branca, frita');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (306, 'Pescados e frutos do mar', 'Pescada, filé, com farinha de trigo, frito');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (307, 'Pescados e frutos do mar', 'Pescada, filé, cru');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (308, 'Pescados e frutos do mar', 'Pescada, filé, frito');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (309, 'Pescados e frutos do mar', 'Pescada, filé, molho escabeche');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (310, 'Pescados e frutos do mar', 'Pescadinha, crua');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (311, 'Pescados e frutos do mar', 'Pintado, assado');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (312, 'Pescados e frutos do mar', 'Pintado, cru');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (313, 'Pescados e frutos do mar', 'Pintado, grelhado');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (314, 'Pescados e frutos do mar', 'Porquinho, cru');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (315, 'Pescados e frutos do mar', 'Salmão, filé, com pele, fresco,  grelhado');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (316, 'Pescados e frutos do mar', 'Salmão, sem pele, fresco, cru');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (317, 'Pescados e frutos do mar', 'Salmão, sem pele, fresco, grelhado');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (318, 'Pescados e frutos do mar', 'Sardinha, assada');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (319, 'Pescados e frutos do mar', 'Sardinha, conserva em óleo');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (320, 'Pescados e frutos do mar', 'Sardinha, frita');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (321, 'Pescados e frutos do mar', 'Sardinha, inteira, crua');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (322, 'Pescados e frutos do mar', 'Tucunaré, filé, congelado, cru');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (323, 'Carnes e derivados', 'Apresuntado');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (324, 'Carnes e derivados', 'Caldo de carne, tablete');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (325, 'Carnes e derivados', 'Caldo de galinha, tablete');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (326, 'Carnes e derivados', 'Carne, bovina, acém, moído, cozido');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (327, 'Carnes e derivados', 'Carne, bovina, acém, moído, cru');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (328, 'Carnes e derivados', 'Carne, bovina, acém, sem gordura, cozido');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (329, 'Carnes e derivados', 'Carne, bovina, acém, sem gordura, cru');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (330, 'Carnes e derivados', 'Carne, bovina, almôndegas, cruas');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (331, 'Carnes e derivados', 'Carne, bovina, almôndegas, fritas');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (332, 'Carnes e derivados', 'Carne, bovina, bucho, cozido');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (333, 'Carnes e derivados', 'Carne, bovina, bucho, cru');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (334, 'Carnes e derivados', 'Carne, bovina, capa de contra-filé, com gordura, crua');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (335, 'Carnes e derivados', 'Carne, bovina, capa de contra-filé, com gordura, grelhada');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (336, 'Carnes e derivados', 'Carne, bovina, capa de contra-filé, sem gordura, crua');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (337, 'Carnes e derivados', 'Carne, bovina, capa de contra-filé, sem gordura, grelhada');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (338, 'Carnes e derivados', 'Carne, bovina, charque, cozido');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (339, 'Carnes e derivados', 'Carne, bovina, charque, cru');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (340, 'Carnes e derivados', 'Carne, bovina, contra-filé, à milanesa');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (341, 'Carnes e derivados', 'Carne, bovina, contra-filé de costela, cru');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (342, 'Carnes e derivados', 'Carne, bovina, contra-filé de costela, grelhado');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (343, 'Carnes e derivados', 'Carne, bovina, contra-filé, com gordura, cru');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (344, 'Carnes e derivados', 'Carne, bovina, contra-filé, com gordura, grelhado');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (345, 'Carnes e derivados', 'Carne, bovina, contra-filé, sem gordura, cru');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (346, 'Carnes e derivados', 'Carne, bovina, contra-filé, sem gordura, grelhado');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (347, 'Carnes e derivados', 'Carne, bovina, costela, assada');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (348, 'Carnes e derivados', 'Carne, bovina, costela, crua');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (349, 'Carnes e derivados', 'Carne, bovina, coxão duro, sem gordura, cozido');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (350, 'Carnes e derivados', 'Carne, bovina, coxão duro, sem gordura, cru');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (351, 'Carnes e derivados', 'Carne, bovina, coxão mole, sem gordura, cozido');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (352, 'Carnes e derivados', 'Carne, bovina, coxão mole, sem gordura, cru');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (353, 'Carnes e derivados', 'Carne, bovina, cupim, assado');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (354, 'Carnes e derivados', 'Carne, bovina, cupim, cru');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (355, 'Carnes e derivados', 'Carne, bovina, fígado, cru');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (356, 'Carnes e derivados', 'Carne, bovina, fígado, grelhado');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (357, 'Carnes e derivados', 'Carne, bovina, filé mingnon, sem gordura, cru');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (358, 'Carnes e derivados', 'Carne, bovina, filé mingnon, sem gordura, grelhado');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (359, 'Carnes e derivados', 'Carne, bovina, flanco, sem gordura, cozido');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (360, 'Carnes e derivados', 'Carne, bovina, flanco, sem gordura, cru');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (361, 'Carnes e derivados', 'Carne, bovina, fraldinha, com gordura, cozida');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (362, 'Carnes e derivados', 'Carne, bovina, fraldinha, com gordura, crua');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (363, 'Carnes e derivados', 'Carne, bovina, lagarto, cozido');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (364, 'Carnes e derivados', 'Carne, bovina, lagarto, cru');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (365, 'Carnes e derivados', 'Carne, bovina, língua, cozida');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (366, 'Carnes e derivados', 'Carne, bovina, língua, crua');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (367, 'Carnes e derivados', 'Carne, bovina, maminha, crua');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (368, 'Carnes e derivados', 'Carne, bovina, maminha, grelhada');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (369, 'Carnes e derivados', 'Carne, bovina, miolo de alcatra, sem gordura, cru');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (370, 'Carnes e derivados', 'Carne, bovina, miolo de alcatra, sem gordura, grelhado');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (371, 'Carnes e derivados', 'Carne, bovina, músculo, sem gordura, cozido');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (372, 'Carnes e derivados', 'Carne, bovina, músculo, sem gordura, cru');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (373, 'Carnes e derivados', 'Carne, bovina, paleta, com gordura, crua');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (374, 'Carnes e derivados', 'Carne, bovina, paleta, sem gordura, cozida');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (375, 'Carnes e derivados', 'Carne, bovina, paleta, sem gordura, crua');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (376, 'Carnes e derivados', 'Carne, bovina, patinho, sem gordura, cru');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (377, 'Carnes e derivados', 'Carne, bovina, patinho, sem gordura, grelhado');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (378, 'Carnes e derivados', 'Carne, bovina, peito, sem gordura, cozido');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (379, 'Carnes e derivados', 'Carne, bovina, peito, sem gordura, cru');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (380, 'Carnes e derivados', 'Carne, bovina, picanha, com gordura, crua');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (381, 'Carnes e derivados', 'Carne, bovina, picanha, com gordura, grelhada');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (382, 'Carnes e derivados', 'Carne, bovina, picanha, sem gordura, crua');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (383, 'Carnes e derivados', 'Carne, bovina, picanha, sem gordura, grelhada');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (384, 'Carnes e derivados', 'Carne, bovina, seca, cozida');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (385, 'Carnes e derivados', 'Carne, bovina, seca, crua');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (386, 'Carnes e derivados', 'Coxinha de frango, frita');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (387, 'Carnes e derivados', 'Croquete, de carne, cru');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (388, 'Carnes e derivados', 'Croquete, de carne, frito');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (389, 'Carnes e derivados', 'Empada de frango, pré-cozida, assada');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (390, 'Carnes e derivados', 'Empada, de frango, pré-cozida');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (391, 'Carnes e derivados', 'Frango, asa, com pele, crua');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (392, 'Carnes e derivados', 'Frango, caipira, inteiro, com pele, cozido');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (393, 'Carnes e derivados', 'Frango, caipira, inteiro, sem pele, cozido');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (394, 'Carnes e derivados', 'Frango, coração, cru');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (395, 'Carnes e derivados', 'Frango, coração, grelhado');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (396, 'Carnes e derivados', 'Frango, coxa, com pele, assada');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (397, 'Carnes e derivados', 'Frango, coxa, com pele, crua');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (398, 'Carnes e derivados', 'Frango, coxa, sem pele, cozida');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (399, 'Carnes e derivados', 'Frango, coxa, sem pele, crua');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (400, 'Carnes e derivados', 'Frango, fígado, cru');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (401, 'Carnes e derivados', 'Frango, filé, à milanesa');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (402, 'Carnes e derivados', 'Frango, inteiro, com pele, cru');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (403, 'Carnes e derivados', 'Frango, inteiro, sem pele, assado');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (404, 'Carnes e derivados', 'Frango, inteiro, sem pele, cozido');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (405, 'Carnes e derivados', 'Frango, inteiro, sem pele, cru');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (406, 'Carnes e derivados', 'Frango, peito, com pele, assado');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (407, 'Carnes e derivados', 'Frango, peito, com pele, cru');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (408, 'Carnes e derivados', 'Frango, peito, sem pele, cozido');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (409, 'Carnes e derivados', 'Frango, peito, sem pele, cru');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (410, 'Carnes e derivados', 'Frango, peito, sem pele, grelhado');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (411, 'Carnes e derivados', 'Frango, sobrecoxa, com pele, assada');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (412, 'Carnes e derivados', 'Frango, sobrecoxa, com pele, crua');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (413, 'Carnes e derivados', 'Frango, sobrecoxa, sem pele, assada');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (414, 'Carnes e derivados', 'Frango, sobrecoxa, sem pele, crua');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (415, 'Carnes e derivados', 'Hambúrguer, bovino, cru');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (416, 'Carnes e derivados', 'Hambúrguer, bovino, frito');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (417, 'Carnes e derivados', 'Hambúrguer, bovino, grelhado');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (418, 'Carnes e derivados', 'Lingüiça, frango, crua');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (419, 'Carnes e derivados', 'Lingüiça, frango, frita');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (420, 'Carnes e derivados', 'Lingüiça, frango, grelhada');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (421, 'Carnes e derivados', 'Lingüiça, porco, crua');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (422, 'Carnes e derivados', 'Lingüiça, porco, frita');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (423, 'Carnes e derivados', 'Lingüiça, porco, grelhada');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (424, 'Carnes e derivados', 'Mortadela');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (425, 'Carnes e derivados', 'Peru, congelado, assado');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (426, 'Carnes e derivados', 'Peru, congelado, cru');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (427, 'Carnes e derivados', 'Porco, bisteca, crua');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (428, 'Carnes e derivados', 'Porco, bisteca, frita');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (429, 'Carnes e derivados', 'Porco, bisteca, grelhada');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (430, 'Carnes e derivados', 'Porco, costela, assada');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (431, 'Carnes e derivados', 'Porco, costela, crua');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (432, 'Carnes e derivados', 'Porco, lombo, assado');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (433, 'Carnes e derivados', 'Porco, lombo, cru');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (434, 'Carnes e derivados', 'Porco, orelha, salgada, crua');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (435, 'Carnes e derivados', 'Porco, pernil, assado');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (436, 'Carnes e derivados', 'Porco, pernil, cru');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (437, 'Carnes e derivados', 'Porco, rabo, salgado, cru');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (438, 'Carnes e derivados', 'Presunto, com capa de gordura');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (439, 'Carnes e derivados', 'Presunto, sem capa de gordura');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (440, 'Carnes e derivados', 'Quibe, assado');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (441, 'Carnes e derivados', 'Quibe, cru');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (442, 'Carnes e derivados', 'Quibe, frito');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (443, 'Carnes e derivados', 'Salame');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (444, 'Carnes e derivados', 'Toucinho, cru');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (445, 'Carnes e derivados', 'Toucinho, frito');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (446, 'Leite e derivados', 'Bebida láctea, pêssego');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (447, 'Leite e derivados', 'Creme de Leite');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (448, 'Leite e derivados', 'Iogurte, natural');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (449, 'Leite e derivados', 'Iogurte, natural, desnatado');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (450, 'Leite e derivados', 'Iogurte, sabor abacaxi');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (451, 'Leite e derivados', 'Iogurte, sabor morango');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (452, 'Leite e derivados', 'Iogurte, sabor pêssego');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (453, 'Leite e derivados', 'Leite, condensado');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (454, 'Leite e derivados', 'Leite, de cabra');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (455, 'Leite e derivados', 'Leite, de vaca, achocolatado');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (456, 'Leite e derivados', 'Leite, de vaca, desnatado, pó');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (457, 'Leite e derivados', 'Leite, de vaca, desnatado, UHT');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (458, 'Leite e derivados', 'Leite, de vaca, integral');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (459, 'Leite e derivados', 'Leite, de vaca, integral, pó');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (460, 'Leite e derivados', 'Leite, fermentado');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (461, 'Leite e derivados', 'Queijo, minas, frescal');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (462, 'Leite e derivados', 'Queijo, minas, meia cura');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (463, 'Leite e derivados', 'Queijo, mozarela');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (464, 'Leite e derivados', 'Queijo, parmesão');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (465, 'Leite e derivados', 'Queijo, pasteurizado');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (466, 'Leite e derivados', 'Queijo, petit suisse, morango');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (467, 'Leite e derivados', 'Queijo, prato');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (468, 'Leite e derivados', 'Maria mole');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (469, 'Leite e derivados', 'Queijo, ricota');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (470, 'Bebidas (alcoólicas e não alcoólicas)', 'Bebida isotônica, sabores variados');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (471, 'Bebidas (alcoólicas e não alcoólicas)', 'Café, infusão 10%');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (472, 'Bebidas (alcoólicas e não alcoólicas)', 'Cana, aguardente 1');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (473, 'Bebidas (alcoólicas e não alcoólicas)', 'Cana, caldo de');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (474, 'Bebidas (alcoólicas e não alcoólicas)', 'Cerveja, pilsen 2');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (475, 'Bebidas (alcoólicas e não alcoólicas)', 'Chá, erva-doce, infusão 5%');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (476, 'Bebidas (alcoólicas e não alcoólicas)', 'Chá, mate, infusão 5%');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (477, 'Bebidas (alcoólicas e não alcoólicas)', 'Chá, preto, infusão 5%');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (478, 'Bebidas (alcoólicas e não alcoólicas)', 'Coco, água de');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (479, 'Bebidas (alcoólicas e não alcoólicas)', 'Refrigerante, tipo água tônica');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (480, 'Bebidas (alcoólicas e não alcoólicas)', 'Refrigerante, tipo cola');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (481, 'Bebidas (alcoólicas e não alcoólicas)', 'Refrigerante, tipo guaraná');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (482, 'Bebidas (alcoólicas e não alcoólicas)', 'Refrigerante, tipo laranja');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (483, 'Bebidas (alcoólicas e não alcoólicas)', 'Refrigerante, tipo limão');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (484, 'Ovos e derivados', 'Omelete, de queijo');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (485, 'Ovos e derivados', 'Ovo, de codorna, inteiro, cru');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (486, 'Ovos e derivados', 'Ovo, de galinha, clara, cozida/10minutos');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (487, 'Ovos e derivados', 'Ovo, de galinha, gema, cozida/10minutos');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (488, 'Ovos e derivados', 'Ovo, de galinha, inteiro, cozido/10minutos');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (489, 'Ovos e derivados', 'Ovo, de galinha, inteiro, cru');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (490, 'Ovos e derivados', 'Ovo, de galinha, inteiro, frito');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (491, 'Produtos açucarados', 'Achocolatado, pó');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (492, 'Produtos açucarados', 'Açúcar, cristal');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (493, 'Produtos açucarados', 'Açúcar, mascavo');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (494, 'Produtos açucarados', 'Açúcar, refinado');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (495, 'Produtos açucarados', 'Chocolate, ao leite');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (496, 'Produtos açucarados', 'Chocolate, ao leite, com castanha do Pará');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (497, 'Produtos açucarados', 'Chocolate, ao leite, dietético');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (498, 'Produtos açucarados', 'Chocolate, meio amargo');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (499, 'Produtos açucarados', 'Cocada branca');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (500, 'Produtos açucarados', 'Doce, de abóbora, cremoso');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (501, 'Produtos açucarados', 'Doce, de leite, cremoso');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (502, 'Produtos açucarados', 'Geléia, mocotó, natural');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (503, 'Produtos açucarados', 'Glicose de milho');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (504, 'Produtos açucarados', 'Maria mole');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (505, 'Produtos açucarados', 'Maria mole, coco queimado');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (506, 'Produtos açucarados', 'Marmelada');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (507, 'Produtos açucarados', 'Mel, de abelha');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (508, 'Produtos açucarados', 'Melado');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (509, 'Produtos açucarados', 'Quindim');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (510, 'Produtos açucarados', 'Rapadura');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (511, 'Miscelâneas', 'Café, pó, torrado');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (512, 'Miscelâneas', 'Capuccino, pó');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (513, 'Miscelâneas', 'Fermento em pó, químico');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (514, 'Miscelâneas', 'Fermento, biológico, levedura, tablete');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (515, 'Miscelâneas', 'Gelatina, sabores variados, pó');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (516, 'Miscelâneas', 'Sal, dietético');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (517, 'Miscelâneas', 'Sal, grosso');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (518, 'Miscelâneas', 'Shoyu');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (519, 'Miscelâneas', 'Tempero a base de sal');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (520, 'Outros alimentos industrializados', 'Azeitona, preta, conserva');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (521, 'Outros alimentos industrializados', 'Azeitona, verde, conserva');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (522, 'Outros alimentos industrializados', 'Chantilly, spray, com gordura vegetal');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (523, 'Outros alimentos industrializados', 'Leite, de coco');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (524, 'Outros alimentos industrializados', 'Maionese, tradicional com ovos');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (525, 'Alimentos preparados', 'Acarajé');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (526, 'Alimentos preparados', 'Arroz carreteiro');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (527, 'Alimentos preparados', 'Baião de dois, arroz e feijão-de-corda');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (528, 'Alimentos preparados', 'Barreado');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (529, 'Alimentos preparados', 'Bife à cavalo, com contra filé');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (530, 'Alimentos preparados', 'Bolinho de arroz');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (531, 'Alimentos preparados', 'Camarão à baiana');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (532, 'Alimentos preparados', 'Charuto, de repolho');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (533, 'Alimentos preparados', 'Cuscuz, de milho, cozido com sal');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (534, 'Alimentos preparados', 'Cuscuz, paulista');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (535, 'Alimentos preparados', 'Cuxá, molho');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (536, 'Alimentos preparados', 'Dobradinha');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (537, 'Alimentos preparados', 'Estrogonofe de carne');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (538, 'Alimentos preparados', 'Estrogonofe de frango');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (539, 'Alimentos preparados', 'Feijão tropeiro mineiro');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (540, 'Alimentos preparados', 'Feijoada');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (541, 'Alimentos preparados', 'Frango, com açafrão');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (542, 'Alimentos preparados', 'Macarrão, molho bolognesa');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (543, 'Alimentos preparados', 'Maniçoba');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (544, 'Alimentos preparados', 'Quibebe');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (545, 'Alimentos preparados', 'Salada, de legumes, com maionese');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (546, 'Alimentos preparados', 'Salada, de legumes, cozida no vapor');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (547, 'Alimentos preparados', 'Salpicão, de frango');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (548, 'Alimentos preparados', 'Sarapatel');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (549, 'Alimentos preparados', 'Tabule');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (550, 'Alimentos preparados', 'Tacacá');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (551, 'Alimentos preparados', 'Tapioca, com manteiga');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (552, 'Alimentos preparados', 'Tucupi, com pimenta-de-cheiro');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (553, 'Alimentos preparados', 'Vaca atolada');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (554, 'Alimentos preparados', 'Vatapá');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (555, 'Alimentos preparados', 'Virado à paulista');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (556, 'Alimentos preparados', 'Yakisoba');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (557, 'Leguminosas e derivados', 'Amendoim, grão, cru');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (558, 'Leguminosas e derivados', 'Amendoim, torrado, salgado');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (559, 'Leguminosas e derivados', 'Ervilha, em vagem');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (560, 'Leguminosas e derivados', 'Ervilha, enlatada, drenada');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (561, 'Leguminosas e derivados', 'Feijão, carioca, cozido');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (562, 'Leguminosas e derivados', 'Feijão, carioca, cru');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (563, 'Leguminosas e derivados', 'Feijão, fradinho, cozido');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (564, 'Leguminosas e derivados', 'Feijão, fradinho, cru');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (565, 'Leguminosas e derivados', 'Feijão, jalo, cozido');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (566, 'Leguminosas e derivados', 'Feijão, jalo, cru');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (567, 'Leguminosas e derivados', 'Feijão, preto, cozido');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (568, 'Leguminosas e derivados', 'Feijão, preto, cru');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (569, 'Leguminosas e derivados', 'Feijão, rajado, cozido');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (570, 'Leguminosas e derivados', 'Feijão, rajado, cru');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (571, 'Leguminosas e derivados', 'Feijão, rosinha, cozido');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (572, 'Leguminosas e derivados', 'Feijão, rosinha, cru');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (573, 'Leguminosas e derivados', 'Feijão, roxo, cozido');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (574, 'Leguminosas e derivados', 'Feijão, roxo, cru');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (575, 'Leguminosas e derivados', 'Grão-de-bico, cru');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (576, 'Leguminosas e derivados', 'Guandu, cru');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (577, 'Leguminosas e derivados', 'Lentilha, cozida');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (578, 'Leguminosas e derivados', 'Lentilha, crua');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (579, 'Leguminosas e derivados', 'Paçoca, amendoim');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (580, 'Leguminosas e derivados', 'Pé-de-moleque, amendoim');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (581, 'Leguminosas e derivados', 'Soja, farinha');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (582, 'Leguminosas e derivados', 'Soja, extrato solúvel, natural, fluido');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (583, 'Leguminosas e derivados', 'Soja, extrato solúvel, pó');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (584, 'Leguminosas e derivados', 'Soja, queijo (tofu)');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (585, 'Leguminosas e derivados', 'Tremoço, cru');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (586, 'Leguminosas e derivados', 'Tremoço, em conserva');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (587, 'Nozes e sementes', 'Amêndoa, torrada, salgada');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (588, 'Nozes e sementes', 'Castanha-de-caju, torrada, salgada');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (589, 'Nozes e sementes', 'Castanha-do-Brasil, crua');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (590, 'Nozes e sementes', 'Coco, cru');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (591, 'Nozes e sementes', 'Coco, verde, cru');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (592, 'Nozes e sementes', 'Farinha, de mesocarpo de babaçu, crua');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (593, 'Nozes e sementes', 'Gergelim, semente');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (594, 'Nozes e sementes', 'Linhaça, semente');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (595, 'Nozes e sementes', 'Pinhão, cozido');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (596, 'Nozes e sementes', 'Pupunha, cozida');
INSERT INTO alimento (nutriente_ptr_id, category, nome) VALUES (597, 'Nozes e sementes', 'Noz, crua');
