# Generated by Django 3.0.8 on 2020-10-29 17:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('termos', '0002_auto_20201029_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='termos',
            name='termo',
            field=models.TextField(blank=True, max_length=500, validators=[django.core.validators.MaxLengthValidator(500)]),
        ),
    ]
