# Generated by Django 3.0.8 on 2020-07-20 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_auto_20200720_1547'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='data_nascimento',
        ),
        migrations.RemoveField(
            model_name='user',
            name='idade',
        ),
    ]
