# Generated by Django 3.0.8 on 2020-07-17 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fcred', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dieta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('observacao', models.TextField(blank=True, max_length=600, null=True)),
                ('total_alanine_g', models.FloatField(blank=True, null=True)),
                ('total_arginine_g', models.FloatField(blank=True, null=True)),
                ('total_ashes_g', models.FloatField(blank=True, null=True)),
                ('total_aspartic_g', models.FloatField(blank=True, null=True)),
                ('total_calcium_mg', models.FloatField(blank=True, null=True)),
                ('total_carbohydrate_g', models.FloatField(blank=True, null=True)),
                ('total_cholesterol_mg', models.FloatField(blank=True, null=True)),
                ('total_copper_mg', models.FloatField(blank=True, null=True)),
                ('total_cystine_g', models.FloatField(blank=True, null=True)),
                ('total_energy_kcal', models.FloatField(blank=True, null=True)),
                ('total_energy_kj', models.FloatField(blank=True, null=True)),
                ('total_fiber_g', models.FloatField(blank=True, null=True)),
                ('total_glutamic_g', models.FloatField(blank=True, null=True)),
                ('total_glycine_g', models.FloatField(blank=True, null=True)),
                ('total_histidine_g', models.FloatField(blank=True, null=True)),
                ('total_humidity_percents', models.FloatField(blank=True, null=True)),
                ('total_iron_mg', models.FloatField(blank=True, null=True)),
                ('total_isoleucine_g', models.FloatField(blank=True, null=True)),
                ('total_leucine_g', models.FloatField(blank=True, null=True)),
                ('total_lipidius_g', models.FloatField(blank=True, null=True)),
                ('total_lysine_g', models.FloatField(blank=True, null=True)),
                ('total_magnesium_mg', models.FloatField(blank=True, null=True)),
                ('total_manganes_mg', models.FloatField(blank=True, null=True)),
                ('total_methionine_g', models.FloatField(blank=True, null=True)),
                ('total_monounsaturated_g', models.FloatField(blank=True, null=True)),
                ('total_niacin_mg', models.FloatField(blank=True, null=True)),
                ('total_phenylalanine_g', models.FloatField(blank=True, null=True)),
                ('total_phosphorus_mg', models.FloatField(blank=True, null=True)),
                ('total_polyunsaturated_g', models.FloatField(blank=True, null=True)),
                ('total_potassium_mg', models.FloatField(blank=True, null=True)),
                ('total_proline_g', models.FloatField(blank=True, null=True)),
                ('total_protein_g', models.FloatField(blank=True, null=True)),
                ('total_pyridoxine_mg', models.FloatField(blank=True, null=True)),
                ('total_rae_mcg', models.FloatField(blank=True, null=True)),
                ('total_re_mcg', models.FloatField(blank=True, null=True)),
                ('total_retinol_mcg', models.FloatField(blank=True, null=True)),
                ('total_riboflavin_mg', models.FloatField(blank=True, null=True)),
                ('total_saturated_g', models.FloatField(blank=True, null=True)),
                ('total_serine_g', models.FloatField(blank=True, null=True)),
                ('total_sodium_mg', models.FloatField(blank=True, null=True)),
                ('total_threonine_g', models.FloatField(blank=True, null=True)),
                ('total_tiamina_mg', models.FloatField(blank=True, null=True)),
                ('total_tryptophan_g', models.FloatField(blank=True, null=True)),
                ('total_tyrosine_g', models.FloatField(blank=True, null=True)),
                ('total_valine_g', models.FloatField(blank=True, null=True)),
                ('total_vitaminc_mg', models.FloatField(blank=True, null=True)),
                ('total_zinc_mg', models.FloatField(blank=True, null=True)),
                ('alimentos', models.ManyToManyField(blank=True, to='fcred.Alimento')),
            ],
            options={
                'db_table': 'dieta',
            },
        ),
    ]
