# Generated by Django 3.0.8 on 2020-09-27 05:39

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Indicacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_indicado', models.CharField(max_length=255)),
                ('telefone_indicado', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('efetivada', models.BooleanField(blank=True, null=True)),
                ('autorizado', models.BooleanField(blank=True, null=True)),
                ('descricao', models.CharField(blank=True, max_length=255, null=True)),
                ('data_indicacao', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('EA', 'Em andamento'), ('FC', 'Fechado'), ('EF', 'Efetivado'), ('RC', 'Recusado')], default='EA', max_length=2)),
            ],
            options={
                'verbose_name_plural': 'Indicações',
            },
        ),
    ]
