# Generated by Django 3.0.8 on 2020-09-11 19:58

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Indicacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prospector', models.CharField(max_length=255)),
                ('nome_indicado', models.CharField(max_length=255)),
                ('telefone_indicado', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('efetivada', models.BooleanField()),
            ],
            options={
                'verbose_name_plural': 'Indicações',
            },
        ),
    ]
