# Generated by Django 3.0.8 on 2020-09-27 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
        ('indicacao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicacao',
            name='prospector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.Prospector'),
        ),
    ]
