# Generated by Django 3.0.8 on 2020-09-12 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicacao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicacao',
            name='autorizado',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
