# Generated by Django 3.0.8 on 2020-09-12 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
        ('indicacao', '0002_indicacao_autorizado'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicacao',
            name='descricao',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='indicacao',
            name='prospector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.Prospector'),
        ),
    ]
