# Generated by Django 3.0.8 on 2020-09-12 03:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('indicacao', '0003_auto_20200911_2359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indicacao',
            name='nome_indicado',
        ),
        migrations.AddField(
            model_name='indicacao',
            name='data_indicacao',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
