# Generated by Django 3.0.8 on 2020-09-12 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicacao', '0004_auto_20200912_0042'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicacao',
            name='nome_indicado',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
