# Generated by Django 3.0.8 on 2020-09-12 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indicacao', '0006_auto_20200912_0235'),
    ]

    operations = [
        migrations.RenameField(
            model_name='indicacao',
            old_name='year_in_school',
            new_name='status',
        ),
    ]
